# Default values for stl4-01-order-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 3
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

image:
  repository: 073874858801.dkr.ecr.ap-southeast-2.amazonaws.com/stl4-01-order-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "staging"

imagePullSecrets:
  - name: stl-ecr-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

podHostAliases: []

securityContext: {}

env: []

ports:
  - name: main-port
    containerPort: 8082
    protocol: TCP

configmapVolume:
  enabled: false

service:
  name: main-port
  type: ClusterIP
  port: 80
  targetPort: 8082

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
